name: Unit tests
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install pytest and seqparser
        run: |
          python -m pip install pytest
          python -m pip install .
      - name: Run unit tests
        run: pytest -vv